Specify node version for deploy fix attempt
Looks like the deploy was failing due to the following message:

    "TypeError: Object.values is not a function"

Since I didn't have a phoenix static buildpack file to specify the Node
version, it was defaulting to Node 6.9.2 on Heroku. Hopefully this
commit will update the Node version and resolve the issues (without
creating others).